### ISSUE TITLE
Deadlock issue for some of the plugins.

### ISSUE THREAD

**Issue by saganshul** [owtf/owtf#749] opened 2016-09-30 01:12 UTC
There seem to be deadlock issues on the following plugins: 
"semi-passive / session management schema",
"Plugin: Http Methods And Xst (web/active)"
0 results for: ps -ef | grep -i hoppy | grep -v grep
## Your Environment
- Operating System and version (like Kali, Debian, ArchLinux, etc): Kali2

**Comment by delta24** [comment] 2016-09-30 01:14
Yup, I also noticed this issue in a pentest - can you look more into it?

**Comment by DarKnight24** [comment] 2016-10-01 08:41
@delta24 @saganshul  I am not able to reproduce anything for `"Plugin: Http Methods And Xst (web/active)"`. Please suggest a way to reproduce the problem.

**Comment by DarKnight24** [comment] 2016-10-08 08:56
@saganshul Did you face the problem again?

**Comment by delta24** [comment] 2016-12-29 17:21
@DarKnight24 this will always result in a deadlock because of https://github.com/owtf/owtf/issues/449.

**Comment by viyatb** [comment] 2017-07-08 16:31
Closing as duplicate of https://github.com/owtf/owtf/issues/695.

**Closed by viyatb** 2017-07-08 16:31 UTC
Labels: Bug, Moderate Fix
