### ISSUE TITLE
"msfcli" no longer in metasploit

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#491] opened 2015-07-28 11:19 UTC
![screenshot from 2015-07-28 12 49 21](https://cloud.githubusercontent.com/assets/10975138/8930118/038e0752-34f9-11e5-8a25-5349e2efec31.png)
In a new update of kali msfcli has been removed (refer https://community.rapid7.com/community/metasploit/blog for more info), so all metasploit plugins are showing "/bin/sh: 1: /opt/metasploit/apps/pro/msf3/msfcli: not found".

**Comment by DePierre** [comment] 2015-07-28 11:24
Duplicate of #399

**Closed by DePierre** 2015-07-28 11:24 UTC
