### ISSUE TITLE
[lions_2014] Workers disappear sometimes.

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#223] opened 2014-05-22 10:15 UTC
When browsing the *Workers* tab, sometimes the page will be blank even though there are workers running.

Example: Running w3af plugin
The workers are correctly shown.
![workers_ok](https://cloud.githubusercontent.com/assets/923297/3052295/c7399014-e198-11e3-9099-319ab408d8c6.png)
After several refresh, no workers are shown.
![workers_ko](https://cloud.githubusercontent.com/assets/923297/3052296/caabb4e8-e198-11e3-87fb-82b9faa071fb.png)

How to reproduce the bug:
1. Run OWTF (lions_2014 branch)
2. Select a target
3. Run a plugin (anyone)
4. Go to the *Workers* tab
5. Refresh until no workers are shown

*This ui branch is also affected.*

**Comment by delta24** [comment] 2016-02-01 15:03
I cannot reproduce this bug, maybe it has been fixed indirectly in the `develop` branch. I'll reopen if it pops up again. :)

**Closed by delta24** 2016-02-01 15:03 UTC
Labels: Bug
