### ISSUE TITLE
modern httprint alternative or updated signatures

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#25] opened 2013-05-22 17:27 UTC
The goal here is to try to determine with some degree of accuracy the web server version in use even when the banner is not shown or is misleading (whatweb, nmap and other alternatives do not seem to do this very well)

httprint signatures have not been updated since 2004 or so.

We need to implement some of the following:
1) Generate httprint signatures for modern web servers (using a script through shodan results?) and make httprint useful again
2) Find a modern httprint alternative
3) Implement something better than httprint, doing some degree of 1) too obviously

Potentially useful links:
http://arxiv.org/pdf/1305.0245v1.pdf
http://anantshri.info/articles/web_app_finger_printing.html
https://www.owasp.org/index.php/Testing_for_Web_Application_Fingerprint_%28OWASP-IG-004%29

Potential Alternatives:
https://github.com/Mebus/hmap

Perhaps worth analysing:
AppPrint (Beta)
Web, Application Server and Web 2.0 Fingerprinting tool (Beta)
http://www.blueinfy.com/tools.html
http://www.slideshare.net/blueinfy/appprint-web-server-and-applciation-fingerprinting

**Comment by anantshri** [comment] 2016-01-16 19:09
i can see multiple commits around this can anyone confirm what's the current status here.

**Comment by islamoc** [comment] 2016-01-16 19:11
Hello I have updated the list with new signatures from servers with confirmed versions
but it needs to be updated always so the last update I did was Aug 4,2014 by now it is kind of outdated

**Comment by anantshri** [comment] 2016-01-16 19:21
@islamoc if all we are changing is signature.txt i would suggest we add this as part of update process. or a perodic task which ensure's signatures are updated every few days by as simple as curl and save file as signature.txt BTW For reference file location is http://www.net-square.com/signature.txt that will save the overhead of doing this over and over again.

**Comment by islamoc** [comment] 2016-01-16 19:25
the problem is that the file you linked to is not maintained so I had to use the tool to generate signatures of servers that I know their version and add them by my self
there is no way to make it automatic we could use Shodan or something to extract new version and generate signatures automatically but there will be always doubts in the results

**Comment by anantshri** [comment] 2016-01-16 19:41
Ah interesting, so i suppose this is something you are doing as a individual effort. Just overstepping a bit but did you tried also submitting signatures to net-square folks. that will help everyone and that way we can rely on sinature file which may be you are maintaining and then we do pull directly. also everyone else directly using http-print might also benefit from it.

**Comment by delta24** [comment] 2016-03-21 05:43
@islamoc ?

**Comment by islamoc** [comment] 2016-04-04 23:01
sorry for taking long
even if we submitted the signatures need to be updated regularly

**Comment by delta24** [comment] 2016-05-05 04:33
I am closing this issue because I've not found any modern alternative and @islamoc is right: the only solution is to update the signatures regularly.

**Closed by delta24** 2016-05-05 04:33 UTC
Labels: Enhancement
