### ISSUE TITLE
[develop] crash after install on latest kali: column test_groups.priority does not exist

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#512] opened 2015-08-31 13:56 UTC
I just did the following on an old Kali VM:
apt-get update; apt-get upgrade; apt-get dist-upgrade

Then did:
cd /root/owtf_develop/install
python install.py

Everything seemed to work OK on the installer, but when trying to run owtf I got this:
NOTE: I suppose the database schema has changed, the installer should take this into account and upgrade or prompt the user to upgrade the DB structure, instead of crashing like that. Obviously, old database reports should be opened without a problem on newer OWTF versions, that is what every user will expect! :)

```
./owtf.py 

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
Traceback (most recent call last):
  File "./owtf.py", line 272, in <module>
    main(sys.argv)
  File "./owtf.py", line 235, in main
    ComponentInitialiser.initialisation_phase_1(root_dir, owtf_pid)
  File "/root/owtf_develop/framework/dependency_management/component_initialiser.py", line 69, in initialisation_phase_1
    PluginDB()
  File "/root/owtf_develop/framework/db/plugin_manager.py", line 24, in __init__
    self.LoadWebTestGroups(self.config.FrameworkConfigGet("WEB_TEST_GROUPS"))
  File "/root/owtf_develop/framework/db/plugin_manager.py", line 56, in LoadWebTestGroups
    group="web")
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1613, in merge
    load=load, _recursive=_recursive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1652, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 820, in get
    return loading.load_on_ident(self, key)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 231, in load_on_ident
    return q.one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2369, in one
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) column test_groups.priority does not exist
LINE 1: ..._groups_hint, test_groups.url AS test_groups_url, test_group...
                                                             ^
 'SELECT test_groups.code AS test_groups_code, test_groups."group" AS test_groups_group, test_groups.descrip AS test_groups_descrip, test_groups.hint AS test_groups_hint, test_groups.url AS test_groups_url, test_groups.priority AS test_groups_priority \nFROM test_groups \nWHERE test_groups.code = %(param_1)s' {'param_1': 'OWTF-IG-001'}

```

**Comment by DoomTaper** [comment] 2015-08-31 15:44
duplicate of #496 .

**Closed** 2015-08-31 15:48 UTC
