### ISSUE TITLE
Weird behaviour with https targets

### ISSUE THREAD

**Issue by tunnelshade** [owtf/owtf#316] opened 2014-09-08 06:43 UTC
When requests go over a https channel, the requests have relative path as their url i.e

```
GET / HTTP/1.1
Host: somesite.com:443
```

So, when we try to search the transaction db for url `https://somesite.com`, we will not get a hit even when the transaction is actually present

**Comment by delta24** [comment] 2016-05-05 05:00
Cannot reproduce now, must have been fixed in the develop branch.

**Comment by delta24** [comment] 2016-07-09 14:34
Is very reproducible - breaks Spiders, Crawlers and Robots (passive, semi_passive) plugins! :(

**Comment by a0xnirudh** [comment] 2016-07-26 06:58
@delta24 I think the reason for this is not because we use https. It breaks with `'http`, `https` or even if we don't specify any protocol at all.

**Comment by delta24** [comment] 2016-07-26 14:55
@a0xnirudh the Spiders, Robots, and Crawlers semi-passive plugin breaks on `https` but works on `http` targets but the passive plugin breaks on any target.

**Comment by viyatb** [comment] 2017-10-22 04:36
Cannot reproduce in `develop` anymore.

**Closed by viyatb** 2017-10-22 04:36 UTC
Labels: Bug, Priority High
