### ISSUE TITLE
NameError: name 'PROTOCOL_TLS' is not defined

### ISSUE THREAD

**Issue by jack17529** [owtf/owtf#815] opened 2017-02-10 15:37 UTC
using python owtf.py gives this in my ubuntu 16.04

## Expected Behavior
should have started.

## Current Behavior
did not

**Comment by delta24** [comment] 2017-02-10 16:53
@jack17529 can you provide the complete traceback?

**Comment by jack17529** [comment] 2017-02-10 17:23
(owtf) jack@jack-Latitude-3460:~/owtf$ python owtf.py
Traceback (most recent call last):
  File "owtf.py", line 13, in <module>
    from framework.dependency_check import verify_dependencies
  File "/home/jack/owtf/framework/dependency_check.py", line 11, in <module>
    import pip
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in <module>
    from .packages.ssl_match_hostname import CertificateError
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
  File "/home/jack/.virtualenvs/owtf/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py", line 3, in <module>
    from ssl import CertificateError, match_hostname
  File "/usr/lib/python2.7/ssl.py", line 133, in <module>
    PROTOCOL_SSLv23 = PROTOCOL_TLS
NameError: name 'PROTOCOL_TLS' is not defined

**Comment by delta24** [comment] 2017-02-10 17:32
Duplicate of https://github.com/owtf/owtf/issues/812.
- Update your distro
- Update PyOpenSSL and cryptography libraries

**Closed by delta24** 2017-02-10 17:32 UTC
