### ISSUE TITLE
Report enhancements - Pentext XML

### ISSUE THREAD

**Issue by csk** [owtf/owtf#849] opened 2017-05-04 23:24 UTC
About "OWASP OWTF - Report enhancements" feature request. https://www.owasp.org/index.php/OWASP_Code_Sprint_2017#OWASP_OWTF_-_Report_enhancements 

## Expected Behavior

Export a nice report with template, findings, and additional pentester's notes into multiple formats.

## Current Behavior

Currently the tool has a report plugin which show a javascript/html report showing a parsed plugin output.

## Possible Solution

There is a project of radicallyopensecurity guys called Pentext. Since mid 2016 its officialy a OWASP project. https://www.owasp.org/index.php/OWASP_PenText_Project . The project 

> is a collection of XML templates, XML schemas and XSLT code, which combined provide an easy way to generate IT security documents including test reports

Then there is great project called Pandoc which allows to export from many formats to many formats. The supported XML format is Docbook.

I was thinking in writing an xslt which transforms the pentext xml to a docbook. Thelater could then be passed as input to pandoc to export it to formats like: html, odt, docx, pdf (latex, wkhtmltopdf), epub ... .

I will appreciate feedback about this . :)

**Comment by viyatb** [comment] 2017-05-05 16:49
Hey @csk, did you take a look at https://github.com/owtf/reboot/issues/17? 
While Pentext sounds good, it might be difficult to integrate with OWTF as we are moving towards a full React.js based web interface.

**Comment by csk** [comment] 2017-05-05 18:34
Thx for the quick response! I am a bit confused about the owtt/reboot respository. It's like a full remake of owtf? Should this issue be part of owtf/reboot also?

I understand willing to move the frontend to React.js and the report stuff with it, but anyways there is a need of a standard xml format to export to and the frontend shouldn't have to do with it as the xml is build querying the DB. I am thinking in a module which can automagically generate a report like https://www.offensive-security.com/reports/sample-penetration-testing-report.pdf using the owtf collected data .

**Comment by viyatb** [comment] 2017-05-05 18:40
Re: owtf/reboot repository is a place to write and discuss potential new ideas for OWTF (breaking new features).

Yes, I agree that XML would help in structuring the data from the DB into a nice report. Can you explain in a little bit more detail how you would integrate it with React based web interface? I was thinking in terms of having a separate "Report" builder where the user can have additional formatting options before exporting. For that, a nice markdown-based editor or something similar is needed.

**Comment by csk** [comment] 2017-05-05 19:11
For a pentest report, owtf still misses information like title, logos, version control, executive summary, conclusions, etc ... whatever section and subsections the pentester needs. OWTF will still need a web interface (React or not) so the user can write this part of the report and store it in the db (probably per session). I agree that markdown would be nice. The findings part of the report is generated using the plugin_output table and others. Each markdown section  (header1, header2 ... ) will then be transformed to a Pentext <section> element. Each finding will be a <finding> element.

**Comment by viyatb** [comment] 2017-05-05 19:29
@csk yes, exactly. This is why I said that we need to include a separate report builder to let user add  their own templates, and format the data according to their needs. I think Markdown wins in this case and then we can convert the Markdown markup to PDF or any other format for export.

**Comment by viyatb** [comment] 2017-07-08 16:26
Closing as duplicate of https://github.com/owtf/owtf/issues/695.

**Closed by viyatb** 2017-07-08 16:26 UTC
