### ISSUE TITLE
Settings > HTTP AUTH

### ISSUE THREAD

**Issue by leebaird** [owtf/owtf#369] opened 2014-11-20 19:46 UTC
Add Domain.

Add pop-up list to HTTP AUTH MODE:
     Basic
     Digest
     NTLMv2
     NTLMv3

**Comment by 7a** [comment] 2015-01-26 19:44
@leebaird Could you please elaborate a bit more on this?

1) What do you mean by "Add Domain"? 
Can you not do this via "Add Target"? A target CAN be a domain, an IP address or a URL. Please note that if you use a domain or an IP address you are telling OWTF to perform a network assessment, this will port scan the host, etc.

2) re "Add pop-up list to HTTP AUTH MODE:"
Are you asking for a UI change or for extended support of more authentication modes?
If asking for a UI change, I understand we could achieve the same via a dropdown list with the allowed values for HTTP_AUTH_MODE, would that be OK?
At the moment, we do not support authentication modes other than basic, so this UI change would be just "cosmetic" if you know what I mean :)

**Comment by delta24** [comment] 2016-01-29 09:34
Duplicate of #264.  The referrenced issue is more relevant than this.

**Closed by delta24** 2016-01-29 09:34 UTC
Labels: Enhancement, Feature
