### ISSUE TITLE
Workers can be set to Zero

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#306] opened 2014-08-27 16:28 UTC
The user is allowed to kill all of the workers and run plug-ins with no workers left. This situation is not handled by OWTF and of course this is causing a crash.

Error Message:

A plug-in is allowed to run without workers 

Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/kour/owtf/framework/lib/owtf_process.py", line 74, in run
    self.pseudo_run()
  File "/home/kour/owtf/framework/http/proxy/transaction_logger.py", line 103, in pseudo_run
    self.core.DB.Transaction.LogTransactionsFromLogger(transactions_dict)
  File "/home/kour/owtf/framework/db/transaction_manager.py", line 290, in LogTransactionsFromLogger
    self.LogTransactions(transaction_list, target_id)
  File "/home/kour/owtf/framework/db/transaction_manager.py", line 225, in LogTransactions
    session = Session()
TypeError: 'NoneType' object is not callable

**Comment by DePierre** [comment] 2015-01-26 19:43
@marioskourtesis Have you been able to reproduce the error since? Because I tried a lot but I was not able to set the number of workers to 0. Please let us now ;)

**Comment by tunnelshade** [comment] 2015-02-09 18:16
This is an old bug, which is fixed in both stable and develop

**Closed by tunnelshade** 2015-02-09 18:16 UTC
Labels: Bug
