### ISSUE TITLE
Failed to launch on Kali Linux

### ISSUE THREAD

**Issue by 9r0x** [owtf/owtf#1014] opened 2019-03-11 16:44 UTC
After cloning the repo, starting the server manually, and `python setup.py develop`, `owtf` command is reporting error.

## Expected Behavior
Running properly

## Current Behavior
Not running and error is reported

## Possible Solution
run `python setup.py develop` again and see two lines of error:
```
Collecting black==18.4a3
  Could not find a version that satisfies the requirement black==18.4a3 (from versions: )
No matching distribution found for black==18.4a3
```
```
error /root/owtf/owtf/webapp/node_modules/pngquant-bin: Command failed.
Exit code: 1
```

Not sure if this is the problem.
Also, could be a database related problem since the error reported is a SQL instruction.

```
[SQL: 'SELECT DISTINCT plugins."group" AS plugins_group \nFROM plugins']
```

## Steps to Reproduce (for bugs)
1. Clone the repo
2. Start pgsql with `sudo systemctl enable postgresql`
3. Create user with `sudo su postgres -c "psql -c \"CREATE USER $db_user WITH PASSWORD '$db_pass'\""`, user name is `export db_user="owtf_db_user"`, pass is `export db_pass="jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g="`
4. Create database with `sudo su postgres -c "psql -c \"CREATE DATABASE $db_name WITH OWNER $db_user ENCODING 'utf-8' TEMPLATE template0;\""`, database name is `export db_name="owtf_db"`
5. `owtf`, which reports error

## Logs
owtf_review:
```
[DEBUG] [2019-03-11 12:37:57,457] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
[DEBUG] [2019-03-11 12:37:57,466] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
```

The error reported is [here](https://pastebin.com/fT0Nj2Yk)

## Context
It would be great if it can launch:)

## Your Environment
- Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux
- Up-to-date branch 
- pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

**Comment by EddieIvan01** [comment] 2019-03-12 05:18
I got this issue as well, and  no solution has been found since yesterday. 

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "plugins" does not exist
LINE 2: FROM plugins
             ^
 [SQL: 'SELECT DISTINCT plugins."group" AS plugins_group \nFROM plugins']
```

**Comment by viyatb** [comment] 2019-03-18 16:35
@9r0x @EddieIvan01 thanks for the report! I'll look into this tonight. In the meantime, can you try running the PostgreSQL database in a Docker container (`make startdb`)?

**Comment by 9r0x** [comment] 2019-03-18 17:56
@viyatb I still see the same issue after switching to the PostgreSQL database in a Docker container.

**Comment by propmasterb** [comment] 2019-03-21 19:08
Good afternoon.  I've been trying to get OWTF running in the 2019.1 Kali VM and I am experiencing the same error message when attempting to launch owtf.  I tried multiple times, starting with a fresh VM each time and I keep encountering the same error.

**Comment by viyatb** [comment] 2019-03-21 20:00
can you list what steps you followed and the logs from `owtf_review` directory (if any)? I am able to run OWTF with Postgres in a Docker container on macOS. I'll check on Kali.

**Comment by propmasterb** [comment] 2019-03-22 13:16
Thanks!  Here's the steps I followed:
Downloaded and ran the latest Kali VM (2019.1 64-bit).
Cloned OWTF git repository.
Started and configured Postgresql database per the instructions at the top of this page.
Ran Python setup.py develop
Attempted to run owtf - notified of missing dependencies.
Installed all missing dependencies (pip install XYZ)
Ran "pip check owtf" to verify all dependencies met
launched owtf to receive the error above.

Here's the logs:
[DEBUG] [2019-03-21 16:00:59,973] [File 'error.py', line 125, in log_and_exit_handler] - LocalWorker-1: caught signal SIGINT, exiting
[DEBUG] [2019-03-21 16:00:59,973] [File 'error.py', line 125, in log_and_exit_handler] - LocalWorker-2: caught signal SIGINT, exiting
[DEBUG] [2019-03-21 16:00:59,972] [File 'error.py', line 125, in log_and_exit_handler] - LocalWorker-3: caught signal SIGINT, exiting
[DEBUG] [2019-03-21 16:00:59,972] [File 'error.py', line 125, in log_and_exit_handler] - LocalWorker-4: caught signal SIGINT, exiting
[DEBUG] [2019-03-21 16:00:53,121] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
[DEBUG] [2019-03-21 16:00:53,149] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
[DEBUG] [2019-03-21 16:00:53,161] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
[DEBUG] [2019-03-21 16:00:53,196] [File 'worker.py', line 100, in spawn_worker] - Adding a new worker
[DEBUG] [2019-03-21 16:00:59,977] [File 'error.py', line 125, in log_and_exit_handler] - MainProcess: caught signal SIGINT, exiting

Thank you for your help!

**Comment by propmasterb** [comment] 2019-03-22 15:36
OK - update.  I tried installing owtf on Kali 2018.2 (an older VM image I had on-hand) following the same steps and I got the same error.  I will note that there were significantly fewer dependency issues (on the 2019 Kali, many of the requirements were a version or two older than what was present in Kali).

However, I decided to start over in another fresh Kali 2019.1 64-bit VM with Docker.  I installed Docker on the fresh VM, then cloned the owtf-docker repository as noted in the readme file at <github>/owtf/owtf-docker.  

Then ran "docker build -t <unique name> <path to docker file>" per the aforementioned readme file.  Installation ran smoothly.  I then launched OWTF via:

 docker run -it -p 8008:8008 -p 8009:8009 -p 8010:8010 <image name> /bin/bash

and everything appears to be working.  Dashboard comes up fine.  :)

**Comment by sachinkamath** [comment] 2019-03-25 10:15
I was trying to setup OWTF on Arch Linux (blackarch, specifically) and came across the same bug, Is there a migration script available anywhere?

**Comment by sachinkamath** [comment] 2019-03-25 10:21
Nothing in debug logs in `owtf_review`

Please find some info below : 

```$ sudo netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::5432  
```
The docker version of psql is running just fine.

```$ pip check owtf
No broken requirements found.
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Pip does not report any errors as well

Now when I try to run OWTF, I get the following error: 

```$ owtf
Traceback (most recent call last):
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "plugins" does not exist
LINE 2: FROM plugins
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neo/.virtualenvs/owtf/bin/owtf", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/neo/projects/owtf/bin/owtf", line 7, in <module>
    from owtf.core import main
  File "/home/neo/projects/owtf/owtf/core.py", line 18, in <module>
    from owtf.api.main import start_server
  File "/home/neo/projects/owtf/owtf/api/main.py", line 15, in <module>
    from owtf.api.routes import API_v1_HANDLERS, UI_HANDLERS
  File "/home/neo/projects/owtf/owtf/api/routes.py", line 32, in <module>
    plugin_group_re = "(%s)?" % "|".join(Plugin.get_all_plugin_groups(session))
  File "/home/neo/projects/owtf/owtf/models/plugin.py", line 76, in get_all_plugin_groups
    groups = session.query(Plugin.group).distinct().all()
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/neo/.virtualenvs/owtf/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "plugins" does not exist
LINE 2: FROM plugins
             ^
 [SQL: 'SELECT DISTINCT plugins."group" AS plugins_group \nFROM plugins']
```

**Comment by viyatb** [comment] 2019-03-25 17:14
@sachinkamath can you try using Kali 2018 version? I haven't tested this in latest one. It should work on macOS as well.

**Comment by sachinkamath** [comment] 2019-03-27 10:15
@viyatb I don't have access to Kali right now. Let me try a VM.

But I don't see why the operating system is a dependency here. It looks like the table schema is not being populated somehow.

**Comment by viyatb** [comment] 2019-03-27 15:53
I don’t think you need Kali to test it out. I’m trying to make OWTF to be
available on all platforms through Docker.

**Comment by sachinkamath** [comment] 2019-03-27 16:58
@viyatb I was going through the installation steps and saw that there is no configuration being done for database. I don't see any migrations happening in postgresql here.

Also noticed that there is no configuration file for database in `~/.owtf/` folder as well. Am I missing something?

**Comment by viyatb** [comment] 2019-03-28 03:44
@sachinkamath I removed the automated database script stuff from the install script since it did not work on other platforms and it was more of PITA to maintain it.
You can always use PostgreSQL in a Docker container by running `make startdb`. In the default configuration, it should automatically work.

**Comment by viyatb** [comment] 2019-03-28 04:20
This should be fixed in https://github.com/owtf/owtf/commit/79d955694859036e194f90b6e0f594a84ae0114e. `git pull origin develop && python setup.py develop` should fix existing installations. There was a regression in a previous commit which introduced some refactoring in the database session handling.

**Closed by viyatb** 2019-03-28 04:20 UTC

**Comment by sachinkamath** [comment] 2019-03-29 06:20
@viyatb Thanks!! That fixed it :dancer:
