### ISSUE TITLE
select all plugin not working on GUI

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#674] opened 2016-04-21 20:59 UTC
## Expected Behavior

After clicking on select all plugin checkbox and running them owtf should add them to worklist

## Current Behavior

After clicking on select all plugin checkbox and running I got the error "Oops! Server replied: Internal Server Error"

## Possible Solution

I did a checkout to a previous commit of [6 feb](https://github.com/owtf/owtf/commit/552209723aaf) and it was working fine because I knew I have tested it before and was working. So, some recent changes broke it.

## Steps to Reproduce (for bugs)

1. Select a target and then click on select all checkbox
2. Run the plugin
3. You can see the error behind

See the screenshot 
![screenshot 90](https://cloud.githubusercontent.com/assets/10975138/14724050/ab84bf8a-0831-11e6-916f-de3a3094962d.png)

## Your Environment

* Installation method used: automatic
* Version/branch used: develop
* Operating System and version (like Kali, Debian, ArchLinux, etc): kali
* sudo access: yes

**Comment by DePierre** [comment] 2016-04-21 21:25
I can't reproduce on my setup. Could you provide the different logs? Especially first ``ui_server.log`` under ``/tmp/owtf/``.

**Comment by DoomTaper** [comment] 2016-04-21 21:38
[ui_server.log.txt](https://github.com/owtf/owtf/files/230777/ui_server.log.txt)

**Comment by delta24** [comment] 2016-05-02 12:28
I can't reproduce - did you try on a clean setup? Your log file suggests some JS error propagating from the frontend (see the JS `NaN` type? :P )

```
DataError: (psycopg2.DataError) invalid input syntax for integer: "NaN"
    LINE 5: ...d AND sessions.id = (1))) AND targets.id IN ('2', 'NaN', 'Na...
                                                                 ^
     [SQL: 'SELECT targets.id AS targets_id, targets.target_url AS targets_target_url, targets.host_ip AS targets_host_ip, targets.port_number AS targets_port_number, targets.url_scheme AS targets_url_scheme, targets.alternative_ips AS targets_alternative_ips, targets.host_name AS targets_host_name, targets.host_path AS targets_host_path, targets.ip_url AS targets_ip_url, targets.top_domain AS targets_top_domain, targets.top_url AS targets_top_url, targets.scope AS targets_scope \nFROM targets \nWHERE (EXISTS (SELECT 1 \nFROM target_session_association, sessions \nWHERE targets.id = target_session_association.target_id AND sessions.id = target_session_association.session_id AND sessions.id = %(id_1)s)) AND targets.id IN (%(id_2)s, %(id_3)s, %(id_4)s, %(id_5)s, %(id_6)s, %(id_7)s, %(id_8)s) ORDER BY targets.id DESC'] [parameters: {'id_2': '2', 'id_3': 'NaN', 'id_1': (1,), 'id_6': 'NaN', 'id_7': 'NaN', 'id_4': 'NaN', 'id_5': 'NaN', 'id_8': 'NaN'}]
```

**Comment by DoomTaper** [comment] 2016-05-02 19:41
@delta24 Yup! my setup seems clean :). I captured the request and in that an extra parameter is sent `id=NaN` along with the proper target_id (see the screenshot). After debugging I get that extra id is created when I click on "select all plugin" checkbox since it doesn't have an target_id so NaN is allotted to it. But I dont know why its happening on my setup :P
![screenshot 94](https://cloud.githubusercontent.com/assets/10975138/14965508/7e5d42b4-10cb-11e6-9b23-f81d8db771d9.png)

**Comment by DoomTaper** [comment] 2016-05-02 20:51
I have got the whole scenario 
1. there is a function ` toggleAll(checkbox)` used by both *plugin_launcher.html* and *target_manager.html* and we are using `{% module Template(...) %}` to include plugin_launcher.html inside target_manager.html
2. So when I click on "select all plugin" checkbox which is inside plugin_launcher.html, instead of calling toggleAll() of plugin_launcher.html it is calling of target_manager.html which is weird because according to [tornado documentation](http://www.tornadoweb.org/en/stable/template.html) **both should have separate namespaces.** 
3. One more weird thing is that how that was working when I checkout to a previous commit of 6 feb
and why it is happening to my system only ?

**Solution**
I added the check that before pushing the total selected checkbox to a variable, if it is an integer which I hope will only come when a target is selected and it is working!. [See here](https://github.com/DoomTaper/owtf/commit/cfef73c64f2850e348e9ba9fc619878cdde562e9). IMO these changes should anyway be applied as it is a check.
Or it seems this issue is some weird system related issue so can we avoid it ?

**Comment by delta24** [comment] 2016-05-05 04:49
@DoomTaper the check is a good thing. Do send a pull request! :+1:

**Comment by DePierre** [comment] 2016-05-05 16:42
@DoomTaper Any update regarding the issue? I personally cannot reproduce it, nor @delta24 apparently. I will therefore remove the Priority High label.

**Comment by DoomTaper** [comment] 2016-05-05 17:25
@DePierre as I told earlier this is some weird system issue. Adding a [check](https://github.com/DoomTaper/owtf/commit/cfef73c64f2850e348e9ba9fc619878cdde562e9) is fixing that on my system and since it is a check so we can add it anyway :)

**Comment by DePierre** [comment] 2016-05-06 21:28
@DoomTaper Feel free to open a PR but this check seems very weird to me. To me, it looks like fixing the consequences of the issue but not the issue itself, if issue there is.

In the worst case scenario, where you can't find a setup to reproduce the error, it would be nice to add a comment on that change, and maybe even link the issue next to it so we know why we are checking for NaN values there.

**Comment by DoomTaper** [comment] 2016-05-07 06:09
@DePierre [here](https://github.com/DoomTaper/owtf/commit/04b944cef0adda71f17768c9bad7b3efa4be91fd) is another solution which IMO particularly fixes the issue rather than fixing the consequences. Will this work for you ?

**Comment by DePierre** [comment] 2016-05-07 11:53
@DoomTaper It looks ulgy to have a function following this naming covention imo.

**Comment by delta24** [comment] 2016-05-17 03:05
@DoomTaper is it still applicable on your end?

**Comment by delta24** [comment] 2016-05-19 10:46
Closing this as cannot reproduce.

**Closed by delta24** 2016-05-19 10:46 UTC
Labels: Bug
