### ISSUE TITLE
Create Zest Script Error

### ISSUE THREAD

**Issue by marioskourtesis** [owtf/owtf#383] opened 2015-01-14 14:45 UTC
[-] __________ 7 - Target: http://xxxxxx.xxx -> Plugin: Application Discovery (passive) __________
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/zest_owtf/mainclass/Tester : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.zest_owtf.mainclass.Tester. Program will exit.

**Comment by marioskourtesis** [comment] 2015-04-05 00:55
I re-tested this issue to a new Kali VM and installation:
The OWTF ouput on the web ui is "Yup! Script Created :D" while in the command line is:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/zest_owtf/mainclass/Tester : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.zest_owtf.mainclass.Tester. Program will exit.



Exception in thread "main" java.lang.UnsupportedClassVersionError: org/zest_owtf/mainclass/Tester : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.zest_owtf.mainclass.Tester. Program will exit.

**Comment by delta24** [comment] 2016-01-19 04:24
@marioskourtesis I can't reproduce the above error. In my case the zest get created perfectly :) and the forward_to_zap and replay works as intended.

**Comment by delta24** [comment] 2016-01-27 10:16
Closing. I'll reopen if there are any more related issues. :)

**Closed by delta24** 2016-01-27 10:16 UTC
Labels: Bug
